//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoalsCharacterSheet.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoalsCharacterSheet.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;
        ///    &lt;strong class=&quot;pad-left&quot;&gt;{Name}:&lt;/strong&gt;&lt;small class=&quot;pad-left&quot;&gt;{Details}&lt;/small&gt;
        ///&lt;/li&gt;
        ///.
        /// </summary>
        internal static string GoalsEffectsBodyItemTemplate {
            get {
                return ResourceManager.GetString("GoalsEffectsBodyItemTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;unstyled&quot; style=&quot;width: 100%&quot;&gt;
        ///    &lt;li&gt;
        ///		{EffectTitle}
        ///    &lt;/li&gt;
        ///    {EffectBody}
        ///&lt;/ul&gt;.
        /// </summary>
        internal static string GoalsEffectsTemplate {
            get {
                return ResourceManager.GetString("GoalsEffectsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong class=&quot;pad-left&quot;&gt;{Name}:&lt;/strong&gt;&lt;span class=&quot;pad-left&quot;&gt;{Details}&lt;/span&gt;.
        /// </summary>
        internal static string GoalsEffectsTitleItem {
            get {
                return ResourceManager.GetString("GoalsEffectsTitleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;{Name}&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///		legend 
        ///		{
        ///			padding:5px;
        ///			margin:5px;
        ///		}
        ///		fieldset 
        ///		{
        ///			border:2px solid #000;
        ///			padding:5px;
        ///			margin:5px;
        ///		}
        ///        td{
        ///            border: thin solid #000000;
        ///            margin: 0px; 
        ///            padding: 0px;
        ///            display: block;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GoalsSheetTemplate {
            get {
                return ResourceManager.GetString("GoalsSheetTemplate", resourceCulture);
            }
        }
    }
}
